name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - prod
jobs:
  build_and_deploy_job:
    if: github.event_name == 'push'

    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          ref: prod
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_WATER_0C7A7E61E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          app_build_command: "npx @azure/static-web-apps-cli build . --api-location ./backend"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "backend" # Api source code path - optional
          output_location: "build" # Built app content directory - optional